using _4sem_oop_lab1.TCP;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using System.Windows;
using System.Windows.Controls;
using System.Windows.Data;
using System.Windows.Documents;
using System.Windows.Input;
using System.Windows.Media;
using System.Windows.Media.Imaging;
using System.Windows.Navigation;
using System.Windows.Shapes;

namespace _4sem_oop_lab1
{
    /// <summary>
    /// Логика взаимодействия для MainWindow.xaml
    /// </summary>
    public partial class MainWindow : Window
    {
        AppContext appContext;


        public MainWindow()
        {
            InitializeComponent();

            appContext = new AppContext();

            //foreach(var note in appContext.Notes)
            //{
            //    NotesList.Items.Add(note.short_text);
            //}

            NotesList.ItemsSource = appContext.Notes.ToList();

            if(appContext.Users.ToList().Count == 1)
            {                
                AccountManageIcon.Source = new BitmapImage(new Uri("logout.png", UriKind.Relative));
            }
            else
            {
                
            }
        }

        private void Add_Click(object sender, RoutedEventArgs e)
        {
            string my_text = "";
            for (int i = 0; i < 50; i++)
            {
                my_text += "a";
            }
            for (int i = 0; i < 50; i++)
            {
                my_text += "b";
            }
            for (int i = 0; i < 50; i++)
            {
                my_text += "b";
            }
            for (int i = 0; i < 50; i++)
            {
                my_text += "b";
            }
            for (int i = 0; i < 50; i++)
            {
                my_text += "b";
            }
            for (int i = 0; i < 50; i++)
            {
                my_text += "b";
            }
            for (int i = 0; i < 50; i++)
            {
                my_text += "b";
            }
            Note note = new Note(my_text);
            note.server_id = -1;
            appContext.Notes.Add(note);

            appContext.SaveChanges();

            NotesList.ItemsSource = appContext.Notes.ToList();

            NoteEditor noteEditor = new NoteEditor(note);

            noteEditor.Owner = this;

            noteEditor.Show();

        }
        
        private void AccountButton_Click(object sender, RoutedEventArgs e)
        {
            if(appContext.Users.ToList().Count == 0)
            {
                Login loginWindow = new Login();

                loginWindow.Owner = this;

                loginWindow.Show();

                this.Visibility = Visibility.Hidden;
            }
            else 
            {
                MessageBoxResult boxResult = MessageBox.Show("Are you sure want to signout?", "Logout",
                MessageBoxButton.YesNo);
                if(boxResult == MessageBoxResult.Yes)
                {
                    foreach (User user in appContext.Users)
                    {
                        appContext.Users.Remove(user);
                    }
                    appContext.SaveChanges();
                    AccountManageIcon.Source = new BitmapImage(new Uri("login.png", UriKind.Relative));
                }
            }
            
        }

        private void Remove_Click(object sender, RoutedEventArgs e)
        {
            
        }

        private void NotesList_AutoGeneratedColumns(object sender, EventArgs e)
        {
            NotesList.Columns.FirstOrDefault(x => x.Header.ToString() == "local_id").Visibility = Visibility.Hidden;
            NotesList.Columns.FirstOrDefault(x => x.Header.ToString() == "server_id").Visibility = Visibility.Hidden;
            NotesList.Columns.FirstOrDefault(x => x.Header.ToString() == "text").Visibility = Visibility.Hidden;
            NotesList.Columns.FirstOrDefault(x => x.Header.ToString() == "text").Header = string.Empty;
        }

        private void Edit_Click(object sender, RoutedEventArgs e)
        {

        }
    }
}
